# See help here: https://github.com/marketplace/actions/labeler

Geti Tune Backend:
  - changed-files:
      - any-glob-to-any-file:
          - "application/backend/**/*"
          - "application/docker/**/*"

Geti Tune UI:
  - changed-files:
      - any-glob-to-any-file:
          - "application/ui/**/*"

TEST:
  - changed-files:
      - any-glob-to-any-file:
          - "library/tests/**/*"
          - "application/backend/tests/**/*"
          - "application/ui/tests/**/*"

DOC:
  - changed-files:
      - any-glob-to-any-file:
          - "**/docs/**/*"
          - "**/*.md"
          - "LICENSE"
          - "third-party-programs.txt"
          - "NOTICE"

BUILD:
  - changed-files:
      - any-glob-to-any-file:
          - ".ci/**/*"
          - ".github/**/*"
          - ".pre-commit-config.yaml"
          - "markdownlint.rb"
          - "**/pyproject.toml"
          - "**/tox.ini"
          - "**/Dockerfile"
          - "MANIFEST.in"

DEPENDENCY:
  - changed-files:
      - any-glob-to-any-file:
          - "**/pyproject.toml"
