ignore:
  - "lib/**/__init__.py"
  - "lib/src/otx/recipes"
  - "lib/src/otx/tools"
  - "lib/**/exportable_code"
  - "lib/src/otx/core/data/transform_libs/mm*.py"
  - "lib/src/otx/core/exporter/mmdeploy.py"
  - "lib/src/otx/core/model/utils"
